fth TRIV is
	sort Elt .
endfth

fmod LIST{X :: TRIV} is
	sorts NeList{X} List{X} .
    subsort NeList{X} < List{X} .
    subsort X$Elt < NeList{X}.

	op EOP : -> List{X} [ctor] .
	op __ : X$Elt List{X} -> NeList{X} [ctor prec 3 id: EOP] .
endfm

view Instruction from TRIV to INSTRUCTION is
    sort Elt to Instruction .
endv

fmod INPUT-LIST is
	pr LIST{Nat} .
endfm

fmod OUTPUT-LIST is
	pr LIST{Nat} .
endfm